<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class EventoRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'nome' => ['required', 'string', 'min:5'],
            'data_inicio' => [
                'required',
                Rule::date()->format('Y-m-d H:i:s')
            ],
            'data_fim' => [
                'required',
                Rule::date()->format('Y-m-d H:i:s'),
                'after:data_inicio'
            ]
        ];
    }

    public function messages()
    {
        return [
            'nome.required' => 'O nome deve ser informado.',
            'nome.string' => 'O nome deve ser no formato texto'

        ];// TODO: Change the autogenerated stub
    }
}
